{% set version = "0.3.5" %}

package:
  name: pysgrid
  version: {{ version }}

source:
  url: https://github.com/sgrid/pysgrid/archive/v{{ version }}.tar.gz
  sha256: f5c5531be9c45651ed18899645bd49e92645da1107a800e7d00560b31aff023a

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy
    - netcdf4

test:
  requires:
    - scipy
    - pytest
    - mock
  imports:
    - pysgrid
  commands:
    - pytest --pyargs pysgrid

about:
  home: https://github.com/sgrid/pysgrid
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'Python package for working with staggered gridded data.'

extra:
  recipe-maintainers:
    - ayan-usgs
    - ocefpaf
    - ChrisBarker-NOAA
