{% set version = "0.1.1" %}

package:
  name: pysgrid
  version: {{ version }}

source:
  url: https://github.com/sgrid/pysgrid/archive/v{{ version }}.tar.gz
  sha256: fa347f2f406dbb7bb1e422eec904fac92a14d936c24e7155cc589f534e84ae7f

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy
    - netcdf4

test:
  requires:
    - scipy
    - pytest
    - mock
  imports:
    - pysgrid
  # commands:
    # - pytest --pyargs pysgrid

about:
  home: https://github.com/sgrid/pysgrid
  license: BSD 3-Clause
  # license_file: LICENSE
  summary: 'Python package for working with staggered gridded data.'

extra:
  recipe-maintainers:
    - ayan-usgs
    - ocefpaf
    - ChrisBarker-NOAA
