{% set version = "0.3.5" %}

package:
  name: pysgrid
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/sgrid/pysgrid/archive/v{{ version }}.tar.gz
  sha256: f5c5531be9c45651ed18899645bd49e92645da1107a800e7d00560b31aff023a

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - netcdf4
  test:
    - cell_tree2d
    - scipy
    - pytest

test:
  imports:
    - pysgrid

  commands:
    - conda inspect linkages -p $PREFIX pysgrid  # [not win]
    - conda inspect objects -p $PREFIX pysgrid  # [osx]
    - pytest --pyargs pysgrid

about:
  home: https://github.com/sgrid/pysgrid
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'Python package for working with staggered gridded data.'

extra:
  recipe-maintainers:
    - ayan-usgs
    - ocefpaf
