travis:
  secure:
    BINSTAR_TOKEN: r0RFxUQqJ6Ksc8cKQ2ICEajY39xTakfCzD69yGYtvSjdIpfxZFDWqGcADsObWXM3u200WzvNa0aLk32TRVPvFYDgRfMcxGvFiMzurB/ccLqEDiEH8rNm8vqtFUNVkSFGMHmSO2KorvtJYPy1huPuB6HhRvlmIgBEVJPsPsLztgFgUX91/azlT605On1L9ZWwuLD//Qabk7RO4Sqw80IOe3JjQi0O7AutEId1g/3h9mPRHRx2zyLm0wFAR5urhBLU8law1cz4CIxq9zX5NyipfqXgSm6+GSoaOhCr7Hti4iUQtr9Il2X5m/MRTeGyYl7hq2KEMmMtuQUANtFefhF/9JoZ2tfv8BrCkj1M0F3IeD5EBULOqzDJUM0Tq7Lu9QxpAxjLD1zbRQ3s8r+TTFStHSFfmkBG3J8NZMZnm1ZZ2daLuri2gl9Qpt2H4G0QLzIAGZNgTC7GhU4c27CSMNk56rkKgcoPpvhJskBJeY7utiZpThjqGNp88okP0Mf/Fg2Qm+AgheYElpwcRAc0wjK7h4c/wjt9mAxoNPllzSRUOFWQiRJ0BHoCXfsjqG5UuQWqk94ABkitEn0J1xV5bI/+xxG3q5BtHnrh9rHWmRtzjpnKMN56dcpWPuXh7EcnMTMCBanIeXyxgC+OqbQd7nsDIWkFjIh/R7whA5o3aGscwcI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
