travis:
  secure:
    BINSTAR_TOKEN: K5vOJ7UkFJ2n0s47llyLftLcSbDGyNrA828QWw4ltJXrBiZny0RJfm3kfb2GaxKHMhvjmpbnGLtFb7a9FT6xz8ATQdsOFWkNkojf3bI5cKKUHHN1F3hho1ocg33fFTpLm1FYXmG2i5kY/8pYdyqgBt+iFwYqhcDzTeLsIQ8jbhjLGsgCpwPTyt7RSFiOFNdR4TVeXS6DqqEIimXQzlM1fj4rcI5X8Or0LVlFa7KM0pyAGlDe2mm6FS1q/YXwpiIbeitRWnMhi+AaoTYJn33WznjkodBpsFrtc8RgJc1JlJ7NqjYyWJV3dg5djmBOm/vrRKZAlX/oG/nA8Y4XR9koEqUmYatxjgz4Xkq21R+LcZk+9MgClW+ezAguJoKwUizrmgyGKBgIubyZfh6YtaBFRjKDfeGYiZHpu2P8HITuHPFEeq+kROTmLS1iEpR+jFONy4mt0eSG5+/r69eW2xvsQW9FSI3Bp/K3H7YCiVe2XQ77F9W3r6Q2UmMJON9243Vh74ZC6+LoDKrPhd5uwz8FfKEcynrsRNusrBorCbQl+MCgyTyTCtrzzLymP8hsLtvVJYoMaZVkzCrDjP7UHHDxV+229NrI12+kAenf6kvWsi3hCY5xr547s65IP9qiLYnH5T0SrCK4u1z0kAGJFWU79LM3+mX0yvce/XzKfeggBN0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
